package(default_visibility = ["//:internal"])

load("//:defs.bzl", "thoth")

thoth(
    deps = [
        # "@gs_tools//src",
        # "@gs_ui//src",
        "//src/data",
        "//types/handlebars",
        "//types/showdown",
    ])